### PR TITLE
Update references in README to v2

### PR DESCRIPTION
**Pull request by dawranliou**
Thank you for your work!  I was trying out this gh action and realized the document wasn't up-to-date.
This PR updates the various references of `v1` and `v2-beta` in the README file to `v2`.

### CODE REVIEW

**Comment by svetlyak40wt** [comment]
Good! Thank you!

**Comment by svetlyak40wt** [comment]
However, README.md is autogenerated file.

The documentation source is here: https://github.com/40ants/setup-lisp/blob/master/docs.lisp#L153. It is used to generate HTML docs https://40ants.com/setup-lisp/ and README.md file.

Could you please move your changes into the docs.lisp file?

**Comment by dawranliou** [comment]
Huge oops!  I saw the README and edited it directly on Github UI and missed it completely.  Yes, I will do it shortly.

I'm still new to the Common Lisp community.  Is it a common practice for repos to have autogenerated READMEs?

Thank you for your time!

**Comment by dawranliou** [comment]
Since the change was minor, I just rewrote the commit so the history is cleaner.  Hope that doesn't disrupt your preferred way to review a PR 🙏 .

**Comment by svetlyak40wt** [comment]
> I'm still new to the Common Lisp community. Is it a common practice for repos to have autogenerated READMEs?

No, it is no. There are many Common Lisp documentation tools (you'll find [my reviews on them here](https://40ants.com/lisp-project-of-the-day/)), however only MGL-PAX and my fork of it [40ANTS-DOC](https://40ants.com/doc/) are supporting the update of HTML and readme simultaneously.

**Pull request merged**
